basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
# http://jsonfeed.org/version/1

# generated guid
id: f08e7360-d408-41f2-8c1b-12e80d6cf6c6
external_url: http://www.webbyawards.com/winners/2017/websites/website-features-and-design/best-visual-design-aesthetic/
title: WEBBY AWARDS IS AN INTERNATIONAL AWARD
image: https://1z3fa82l1ypj1an7rx3zxeet-wpengine.netdna-ssl.com/wp-content/uploads/2017/04/WebbyAwards_600x300.jpg
content_text: The Webbys honors excellence in several major media types including Websites, Film & Video, Advertising, Media & PR, Social, Mobile Sites & Apps, Games, and Podcasts & Digital Audio.
# content_md todo

author: webbyawards

# unix time
date_modified: 1522597134
tags:


