basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
# http://jsonfeed.org/version/1

# generated guid
id: 3d87815a-aa49-40e6-a2f9-f78c626029b8
external_url : http://youtube.com/watch?v=wzAWI9h3q18
title: Do you Even Pug (Jade) bro?
image: /linkBlog/180401b_jade_bro/pug.jpg
content_text: An introduction to Pug(Jade) by Google Designer Travis Neilson. We take an intro look at Jade (now called Pug v1 ), a templating language that is completely awesome and has changed my life.
# content_md todo

author: Travis Neilson

# unix time
date_modified: 1522597131
tags:



