basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
# http://jsonfeed.org/version/1

# generated guid
id: cb42b345-c81c-46e1-826b-abc81fb39934

title: The FWA - showcasing innovation
image: http://upload.wikimedia.org/wikipedia/commons/5/53/Schema_Saeulenordnungen.jpg
content_text: How to do sticky in a column.
# content_md todo

author: Vic

# unix time
date_modified: 1523456235
tags:


