basedir: ../../

id: https://blog.nbake.org/blog/20180425_what_makes_really_great_ui
url: /blog/20180425_what_makes_really_great_ui
title: What Makes Really Great UI
created: April 25, 2018
date_published: '2018-04-25T07:00:00-08:00'
content_html: In this article, we talk about what makes really great UI.
image: /blog/20180425_what_makes_really_great_ui/assets/img/light768.jpg
author:
  name: Wolfgang Gehner
  avatar: /assets/img/wolf.jpg
tags:
- design
- development
- trinity



