basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
# http://jsonfeed.org/version/1

# generated guid
id: 34d8c130-f22f-4045-94fa-5f2e00fc1f04
external_url : https://twitter.com/fwa
title: The FWA - showcasing innovation
image: http://blog.publicisna.com/wp-content/uploads/2014/03/FWA.png
content_text: FWA - showcasing innovation, with the mission is to showcase cutting edge creativity
# content_md todo

author: favorite website awards

# unix time
date_modified: 1522597140
tags:


