basedir: ../../

id: https://blog.nbake.org/blog/20171125_what_makes_great_ux
url: /blog/20171125_what_makes_great_ux
title: What Makes Great UX
created: November 25, 2017
date_published: '2017-11-25T13:00:00-08:00'
content_html: In this article, we talk about what makes a great User Experience.
image: /blog/20171125_what_makes_great_ux/assets/img/city768.jpg
author:
  name: Wolfgang Gehner
  avatar: /assets/img/wolf.jpg
tags:
- design
- management
- trinity

