basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
# http://jsonfeed.org/version/1

# generated guid
id: 211d6fcb-932a-48e0-81cb-e40a37c0f417
external_url : http://twitter.com/chriscoyier
title: Chris Coyier
image: https://chriscoyier.net/wp-content/uploads/2017/06/IMG_8408-1024x1024.jpg
content_text: A tought leader on front end web development. Co-founder of CodePen, a playground for front-end web development.
# content_md todo

author: chris coyier

# unix time
date_modified: 1522799218
tags:


