basedir: \Users\uptim\Documents\GitHub\topseed-dev\www
# http://jsonfeed.org/version/1

# generated guid
id: a31fc60c-1ca9-4b3a-84a3-86285a46f1cf
external_url : http://tympanus.net/codrops/author/crnacura/
title: Manoela
image: https://s3.amazonaws.com/blog.psd2html.com/wp-content/uploads/2015/02/19140008/01_639x296_041.png
content_text: ML is a freelance web designer and developer with a passion for interaction design.
# content_md todo

author: crna cura

# unix time
date_modified: 1522799220
tags:



